const WORD_DATA = [
    { category: 'Ülkeler', citizenWord: 'Türkiye', imposterWord: 'Azerbaycan' },
    { category: 'Ülkeler', citizenWord: 'Almanya', imposterWord: 'Avusturya' },
    { category: 'Ülkeler', citizenWord: 'İspanya', imposterWord: 'Portekiz' },
    { category: 'Ülkeler', citizenWord: 'Japonya', imposterWord: 'Güney Kore' },
    { category: 'Ülkeler', citizenWord: 'Brezilya', imposterWord: 'Arjantin' },
    { category: 'Ülkeler', citizenWord: 'Fransa', imposterWord: 'İtalya' },
    { category: 'Ülkeler', citizenWord: 'Norveç', imposterWord: 'İsveç' },
    { category: 'Ülkeler', citizenWord: 'Mısır', imposterWord: 'Fas' },
    { category: 'Ülkeler', citizenWord: 'ABD', imposterWord: 'Kanada' },
    { category: 'Ülkeler', citizenWord: 'Hindistan', imposterWord: 'Pakistan' },
    { category: 'Ülkeler', citizenWord: 'Rusya', imposterWord: 'Ukrayna' },
    { category: 'Ülkeler', citizenWord: 'Çin', imposterWord: 'Moğolistan' },
    { category: 'Ülkeler', citizenWord: 'Hollanda', imposterWord: 'Belçika' },
    { category: 'Ülkeler', citizenWord: 'Meksika', imposterWord: 'Kolombiya' },
    { category: 'Ülkeler', citizenWord: 'İsviçre', imposterWord: 'Avusturya' },
    { category: 'Ülkeler', citizenWord: 'Tayland', imposterWord: 'Vietnam' },
    { category: 'Ülkeler', citizenWord: 'Avustralya', imposterWord: 'Yeni Zelanda' },
    { category: 'Ülkeler', citizenWord: 'Yunanistan', imposterWord: 'Kıbrıs' },
    { category: 'Ülkeler', citizenWord: 'Suudi Arabistan', imposterWord: 'Katar' },
    { category: 'Şehirler', citizenWord: 'İstanbul', imposterWord: 'Ankara' },
    { category: 'Şehirler', citizenWord: 'İzmir', imposterWord: 'Antalya' },
    { category: 'Şehirler', citizenWord: 'Roma', imposterWord: 'Floransa' },
    { category: 'Şehirler', citizenWord: 'Paris', imposterWord: 'Lyon' },
    { category: 'Şehirler', citizenWord: 'Londra', imposterWord: 'Manchester' },
    { category: 'Şehirler', citizenWord: 'Berlin', imposterWord: 'Münih' },
    { category: 'Şehirler', citizenWord: 'Madrid', imposterWord: 'Barselona' },
    { category: 'Şehirler', citizenWord: 'New York', imposterWord: 'Los Angeles' },
    { category: 'Şehirler', citizenWord: 'Tokyo', imposterWord: 'Osaka' },
    { category: 'Şehirler', citizenWord: 'Moskova', imposterWord: 'St. Petersburg' },
    { category: 'Şehirler', citizenWord: 'Venedik', imposterWord: 'Amsterdam' },
    { category: 'Şehirler', citizenWord: 'Dubai', imposterWord: 'Abu Dabi' },
    { category: 'Şehirler', citizenWord: 'Prag', imposterWord: 'Viyana' },
    { category: 'Şehirler', citizenWord: 'Kahire', imposterWord: 'İskenderiye' },
    { category: 'Şehirler', citizenWord: 'Bakü', imposterWord: 'Tiflis' },
    { category: 'Şehirler', citizenWord: 'Atina', imposterWord: 'Selanik' },
    { category: 'Şehirler', citizenWord: 'Lizbon', imposterWord: 'Porto' },
    { category: 'Şehirler', citizenWord: 'Seul', imposterWord: 'Busan' },
    { category: 'Şehirler', citizenWord: 'Sidney', imposterWord: 'Melbourne' },
    { category: 'Şehirler', citizenWord: 'Rio de Janeiro', imposterWord: 'Sao Paulo' },
    { category: 'Doğa Olayları', citizenWord: 'Fırtına', imposterWord: 'Hortum' },
    { category: 'Doğa Olayları', citizenWord: 'Kar', imposterWord: 'Dolu' },
    { category: 'Doğa Olayları', citizenWord: 'Yağmur', imposterWord: 'Çisenti' },
    { category: 'Doğa Olayları', citizenWord: 'Deprem', imposterWord: 'Tsunami' },
    { category: 'Doğa Olayları', citizenWord: 'Çığ', imposterWord: 'Heyelan' },
    { category: 'Doğa Olayları', citizenWord: 'Gökkuşağı', imposterWord: 'Kuzey Işıkları' },
    { category: 'Doğa Olayları', citizenWord: 'Rüzgar', imposterWord: 'Meltem' },
    { category: 'Doğa Olayları', citizenWord: 'Kuraklık', imposterWord: 'Kıtlık' },
    { category: 'Doğa Olayları', citizenWord: 'Yanardağ', imposterWord: 'Gayzer' },
    { category: 'Doğa Olayları', citizenWord: 'Güneş Tutulması', imposterWord: 'Ay Tutulması' },
    { category: 'Doğa Olayları', citizenWord: 'Kırağı', imposterWord: 'Çiy' },
    { category: 'Doğa Olayları', citizenWord: 'Kasırga', imposterWord: 'Tayfun' },
    { category: 'Doğa Olayları', citizenWord: 'Sıcak Dalgası', imposterWord: 'Kuraklık' },
    { category: 'Doğa Olayları', citizenWord: 'Kum Fırtınası', imposterWord: 'Toz Bulutu' },
    { category: 'Doğa Olayları', citizenWord: 'Gelgit', imposterWord: 'Dalga' },
    { category: 'Doğa Olayları', citizenWord: 'Hortum', imposterWord: 'Kasırga' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Dağ', imposterWord: 'Tepe' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Göl', imposterWord: 'Deniz' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Okyanus', imposterWord: 'Deniz' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Nehir', imposterWord: 'Dere' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Ada', imposterWord: 'Yarımada' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Vadi', imposterWord: 'Kanyon' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Mağara', imposterWord: 'Yeraltı Şehri' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Çöl', imposterWord: 'Vaha' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Ova', imposterWord: 'Plato' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Burun', imposterWord: 'Körfez' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Boğaz', imposterWord: 'Kanal' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Orman', imposterWord: 'Koru' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Bataklık', imposterWord: 'Sazlık' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Volkan', imposterWord: 'Krater' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Delta', imposterWord: 'Haliç' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Kayalık', imposterWord: 'Uçurum' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Bozkır', imposterWord: 'Savan' },
    { category: 'Yeryüzü Şekilleri', citizenWord: 'Mağara', imposterWord: 'Tünel' },
    { category: 'Bitkiler', citizenWord: 'Gül', imposterWord: 'Lale' },
    { category: 'Bitkiler', citizenWord: 'Çam', imposterWord: 'Meşe' },
    { category: 'Bitkiler', citizenWord: 'Papatya', imposterWord: 'Karanfil' },
    { category: 'Bitkiler', citizenWord: 'Orkide', imposterWord: 'Zambak' },
    { category: 'Bitkiler', citizenWord: 'Palmiye', imposterWord: 'Kaktüs' },
    { category: 'Bitkiler', citizenWord: 'Menekşe', imposterWord: 'Sümbül' },
    { category: 'Bitkiler', citizenWord: 'Kavak', imposterWord: 'Söğüt' },
    { category: 'Bitkiler', citizenWord: 'Ayçiçeği', imposterWord: 'Mısır' },
    { category: 'Bitkiler', citizenWord: 'Zeytin Ağacı', imposterWord: 'İncir Ağacı' },
    { category: 'Bitkiler', citizenWord: 'Sarmaşık', imposterWord: 'Yosun' },
    { category: 'Bitkiler', citizenWord: 'Isırgan Otu', imposterWord: 'Nane' },
    { category: 'Bitkiler', citizenWord: 'Bambu', imposterWord: 'Şeker Kamışı' },
    { category: 'Bitkiler', citizenWord: 'Manolya', imposterWord: 'Yasemin' },
    { category: 'Bitkiler', citizenWord: 'Yonca', imposterWord: 'Çim' },
    { category: 'Bitkiler', citizenWord: 'Köknar', imposterWord: 'Ladin' },
    { category: 'Bitkiler', citizenWord: 'Lavanta', imposterWord: 'Biberiye' },
    { category: 'Bitkiler', citizenWord: 'Elma Ağacı', imposterWord: 'Armut Ağacı' },
    { category: 'Bitkiler', citizenWord: 'Aloe Vera', imposterWord: 'Kaktüs' },
    { category: 'Bitkiler', citizenWord: 'Çalı', imposterWord: 'Diken' },
    { category: 'Müzik Türleri', citizenWord: 'Rock', imposterWord: 'Metal' },
    { category: 'Müzik Türleri', citizenWord: 'Pop', imposterWord: 'R&B' },
    { category: 'Müzik Türleri', citizenWord: 'Caz', imposterWord: 'Blues' },
    { category: 'Müzik Türleri', citizenWord: 'Klasik Müzik', imposterWord: 'Opera' },
    { category: 'Müzik Türleri', citizenWord: 'Techno', imposterWord: 'House' },
    { category: 'Müzik Türleri', citizenWord: 'Country', imposterWord: 'Folk' },
    { category: 'Müzik Türleri', citizenWord: 'Reggae', imposterWord: 'Ska' },
    { category: 'Müzik Türleri', citizenWord: 'Türk Sanat Müziği', imposterWord: 'Türk Halk Müziği' },
    { category: 'Müzik Türleri', citizenWord: 'Punk', imposterWord: 'Grunge' },
    { category: 'Müzik Türleri', citizenWord: 'Soul', imposterWord: 'Funk' },
    { category: 'Müzik Türleri', citizenWord: 'K-Pop', imposterWord: 'J-Pop' },
    { category: 'Müzik Türleri', citizenWord: 'Disco', imposterWord: 'Synthpop' },
    { category: 'Müzik Türleri', citizenWord: 'Latino', imposterWord: 'Salsa' },
    { category: 'Müzik Türleri', citizenWord: 'Ambient', imposterWord: 'Chillout' },
    { category: 'Müzik Türleri', citizenWord: 'Dubstep', imposterWord: 'Trap' },
    { category: 'Müzik Türleri', citizenWord: 'Hardstyle', imposterWord: 'Trance' },
    { category: 'Müzik Türleri', citizenWord: 'Flamenko', imposterWord: 'Tango' },
    { category: 'Film Türleri', citizenWord: 'Korku', imposterWord: 'Gerilim' },
    { category: 'Film Türleri', citizenWord: 'Bilim Kurgu', imposterWord: 'Fantastik' },
    { category: 'Film Türleri', citizenWord: 'Aksiyon', imposterWord: 'Macera' },
    { category: 'Film Türleri', citizenWord: 'Dram', imposterWord: 'Trajedi' },
    { category: 'Film Türleri', citizenWord: 'Belgesel', imposterWord: 'Biyografi' },
    { category: 'Film Türleri', citizenWord: 'Animasyon', imposterWord: 'Anime' },
    { category: 'Film Türleri', citizenWord: 'Polisiye', imposterWord: 'Suç' },
    { category: 'Film Türleri', citizenWord: 'Müzikal', imposterWord: 'Dans Filmi' },
    { category: 'Film Türleri', citizenWord: 'Savaş', imposterWord: 'Tarih' },
    { category: 'Film Türleri', citizenWord: 'Gizem', imposterWord: 'Gerilim' },
    { category: 'Film Türleri', citizenWord: 'Kara Film', imposterWord: 'Polisiye' },
    { category: 'Film Türleri', citizenWord: 'Kısa Film', imposterWord: 'Reklam' },
    { category: 'Film Türleri', citizenWord: 'Süper Kahraman', imposterWord: 'Aksiyon' },
    { category: 'Film Türleri', citizenWord: 'Distopya', imposterWord: 'Kıyamet Sonrası' },
    { category: 'Film Türleri', citizenWord: 'Korku', imposterWord: 'Slasher' },
    { category: 'Enstrümanlar', citizenWord: 'Keman', imposterWord: 'Çello' },
    { category: 'Enstrümanlar', citizenWord: 'Gitar', imposterWord: 'Bas Gitar' },
    { category: 'Enstrümanlar', citizenWord: 'Piyano', imposterWord: 'Org' },
    { category: 'Enstrümanlar', citizenWord: 'Flüt', imposterWord: 'Klarnet' },
    { category: 'Enstrümanlar', citizenWord: 'Trompet', imposterWord: 'Saksafon' },
    { category: 'Enstrümanlar', citizenWord: 'Arp', imposterWord: 'Lir' },
    { category: 'Enstrümanlar', citizenWord: 'Ukulele', imposterWord: 'Mandolin' },
    { category: 'Enstrümanlar', citizenWord: 'Kanun', imposterWord: 'Ud' },
    { category: 'Enstrümanlar', citizenWord: 'Darbuka', imposterWord: 'Bongo' },
    { category: 'Enstrümanlar', citizenWord: 'Obua', imposterWord: 'Fagot' },
    { category: 'Enstrümanlar', citizenWord: 'Akordeon', imposterWord: 'Armonika' },
    { category: 'Enstrümanlar', citizenWord: 'Zil', imposterWord: 'Def' },
    { category: 'Enstrümanlar', citizenWord: 'Elektro Gitar', imposterWord: 'Akustik Gitar' },
    { category: 'Enstrümanlar', citizenWord: 'Trombon', imposterWord: 'Tuba' },
    { category: 'Enstrümanlar', citizenWord: 'Ney', imposterWord: 'Kaval' },
    { category: 'Enstrümanlar', citizenWord: 'Kemençe', imposterWord: 'Tulum' },
    { category: 'Enstrümanlar', citizenWord: 'Marimba', imposterWord: 'Ksilofon' },
    { category: 'Edebiyat', citizenWord: 'Şiir', imposterWord: 'Gazel' },
    { category: 'Edebiyat', citizenWord: 'Deneme', imposterWord: 'Makale' },
    { category: 'Edebiyat', citizenWord: 'Masal', imposterWord: 'Fabl' },
    { category: 'Edebiyat', citizenWord: 'Tiyatro Metni', imposterWord: 'Senaryo' },
    { category: 'Edebiyat', citizenWord: 'Ansiklopedi', imposterWord: 'Sözlük' },
    { category: 'Edebiyat', citizenWord: 'Çizgi Roman', imposterWord: 'Manga' },
    { category: 'Edebiyat', citizenWord: 'Günlük', imposterWord: 'Anı' },
    { category: 'Edebiyat', citizenWord: 'Destan', imposterWord: 'Efsane' },
    { category: 'Edebiyat', citizenWord: 'Biyografi', imposterWord: 'Otobiyografi' },
    { category: 'Edebiyat', citizenWord: 'Kompozisyon', imposterWord: 'Deneme' },
    { category: 'Edebiyat', citizenWord: 'Gazete', imposterWord: 'Dergi' },
    { category: 'Edebiyat', citizenWord: 'Atasözü', imposterWord: 'Deyim' },
    { category: 'Edebiyat', citizenWord: 'Hiciv', imposterWord: 'Eleştiri' },
    { category: 'Edebiyat', citizenWord: 'Mektup', imposterWord: 'E-posta' },
    { category: 'Edebiyat', citizenWord: 'Destan', imposterWord: 'Ağıt' },
    { category: 'Edebiyat', citizenWord: 'Masal', imposterWord: 'Destan' },
    { category: 'Sanat & Akımlar', citizenWord: 'Resim', imposterWord: 'Heykel' },
    { category: 'Sanat & Akımlar', citizenWord: 'Fotoğraf', imposterWord: 'Video' },
    { category: 'Sanat & Akımlar', citizenWord: 'Mimari', imposterWord: 'İç Mimari' },
    { category: 'Sanat & Akımlar', citizenWord: 'Seramik', imposterWord: 'Çömlekçilik' },
    { category: 'Sanat & Akımlar', citizenWord: 'Ebru', imposterWord: 'Hat Sanatı' },
    { category: 'Sanat & Akımlar', citizenWord: 'Bale', imposterWord: 'Modern Dans' },
    { category: 'Sanat & Akımlar', citizenWord: 'Tiyatro', imposterWord: 'Sinema' },
    { category: 'Sanat & Akımlar', citizenWord: 'Karikatür', imposterWord: 'İllüstrasyon' },
    { category: 'Sanat & Akımlar', citizenWord: 'Rönesans', imposterWord: 'Barok' },
    { category: 'Sanat & Akımlar', citizenWord: 'Empresyonizm', imposterWord: 'Ekspresyonizm' },
    { category: 'Sanat & Akımlar', citizenWord: 'Kübizm', imposterWord: 'Sürrealizm' },
    { category: 'Sanat & Akımlar', citizenWord: 'Mozaik', imposterWord: 'Vitray' },
    { category: 'Sanat & Akımlar', citizenWord: 'Origami', imposterWord: 'Kirigami' },
    { category: 'Sanat & Akımlar', citizenWord: 'Kaligrafi', imposterWord: 'Tipografi' },
    { category: 'Sanat & Akımlar', citizenWord: 'Moda', imposterWord: 'Tekstil' },
    { category: 'Sanat & Akımlar', citizenWord: 'Gastronomi', imposterWord: 'Aşçılık' },
    { category: 'Sanat & Akımlar', citizenWord: 'Çini', imposterWord: 'Porselen' },
    { category: 'Sanat & Akımlar', citizenWord: 'Animasyon', imposterWord: 'Görsel Efekt' },
    { category: 'Okul Dersleri', citizenWord: 'Fizik', imposterWord: 'Kimya' },
    { category: 'Okul Dersleri', citizenWord: 'Tarih', imposterWord: 'Coğrafya' },
    { category: 'Okul Dersleri', citizenWord: 'Matematik', imposterWord: 'Geometri' },
    { category: 'Okul Dersleri', citizenWord: 'Biyoloji', imposterWord: 'Fen Bilgisi' },
    { category: 'Okul Dersleri', citizenWord: 'Edebiyat', imposterWord: 'Türkçe' },
    { category: 'Okul Dersleri', citizenWord: 'İngilizce', imposterWord: 'Almanca' },
    { category: 'Okul Dersleri', citizenWord: 'Felsefe', imposterWord: 'Mantık' },
    { category: 'Okul Dersleri', citizenWord: 'Resim', imposterWord: 'Müzik' },
    { category: 'Okul Dersleri', citizenWord: 'Din Kültürü', imposterWord: 'Ahlak Bilgisi' },
    { category: 'Okul Dersleri', citizenWord: 'Sosyal Bilgiler', imposterWord: 'Hayat Bilgisi' },
    { category: 'Okul Dersleri', citizenWord: 'Psikoloji', imposterWord: 'Sosyoloji' },
    { category: 'Okul Dersleri', citizenWord: 'Ekonomi', imposterWord: 'İşletme' },
    { category: 'Okul Dersleri', citizenWord: 'Astronomi', imposterWord: 'Uzay Bilimleri' },
    { category: 'Okul Dersleri', citizenWord: 'Hukuk', imposterWord: 'Siyaset' },
    { category: 'Okul Dersleri', citizenWord: 'Arkeoloji', imposterWord: 'Antropoloji' },
    { category: 'Okul Dersleri', citizenWord: 'Tıp', imposterWord: 'Eczacılık' },
    { category: 'Okul Dersleri', citizenWord: 'Mimarlık', imposterWord: 'Mühendislik' },
    { category: 'Okul Dersleri', citizenWord: 'İstatistik', imposterWord: 'Olasılık' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Güneş', imposterWord: 'Ay' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Yıldız', imposterWord: 'Gezegen' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Mars', imposterWord: 'Venüs' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Jüpiter', imposterWord: 'Satürn' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Samanyolu', imposterWord: 'Andromeda' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Kara Delik', imposterWord: 'Beyaz Delik' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Teleskop', imposterWord: 'Dürbün' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Roket', imposterWord: 'Mekik' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Uydu', imposterWord: 'İstasyon' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Kuyruklu Yıldız', imposterWord: 'Asteroit' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Galaksi', imposterWord: 'Bulutsu' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Yerçekimi', imposterWord: 'Manyetizma' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Işık Yılı', imposterWord: 'Parsek' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Yörünge', imposterWord: 'Eksen' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Uzay Gemisi', imposterWord: 'UFO' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Büyük Patlama', imposterWord: 'Kara Enerji' },
    { category: 'Uzay ve Astronomi', citizenWord: 'Krater', imposterWord: 'Dağ' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Kalp', imposterWord: 'Akciğer' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Mide', imposterWord: 'Bağırsak' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Göz', imposterWord: 'Kulak' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Burun', imposterWord: 'Ağız' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Kemik', imposterWord: 'Eklem' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Diş', imposterWord: 'Diş Eti' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Karaciğer', imposterWord: 'Böbrek' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Hormon', imposterWord: 'Enzim' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Virüs', imposterWord: 'Bakteri' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Vitamin', imposterWord: 'Mineral' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Grip', imposterWord: 'Soğuk Algınlığı' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Aşı', imposterWord: 'Serum' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Röntgen', imposterWord: 'MR' },
    { category: 'Vücudumuz ve Sağlık', citizenWord: 'Nabız', imposterWord: 'Tansiyon' },
    { category: 'Elementler ve Kimya', citizenWord: 'Altın', imposterWord: 'Gümüş' },
    { category: 'Elementler ve Kimya', citizenWord: 'Elmas', imposterWord: 'Kömür' },
    { category: 'Elementler ve Kimya', citizenWord: 'Oksijen', imposterWord: 'Azot' },
    { category: 'Elementler ve Kimya', citizenWord: 'Karbon', imposterWord: 'Silikon' },
    { category: 'Elementler ve Kimya', citizenWord: 'Cıva', imposterWord: 'Kurşun' },
    { category: 'Elementler ve Kimya', citizenWord: 'Sodyum', imposterWord: 'Potasyum' },
    { category: 'Elementler ve Kimya', citizenWord: 'Cam', imposterWord: 'Kristal' },
    { category: 'Elementler ve Kimya', citizenWord: 'Kağıt', imposterWord: 'Karton' },
    { category: 'Elementler ve Kimya', citizenWord: 'Alüminyum', imposterWord: 'Teneke' },
    { category: 'Elementler ve Kimya', citizenWord: 'Uranyum', imposterWord: 'Plütonyum' },
    { category: 'Elementler ve Kimya', citizenWord: 'Kireç', imposterWord: 'Çimento' },
    { category: 'Elementler ve Kimya', citizenWord: 'Mermer', imposterWord: 'Granit' },
    { category: 'Elementler ve Kimya', citizenWord: 'Asit', imposterWord: 'Baz' },
    { category: 'Elementler ve Kimya', citizenWord: 'Sıvı', imposterWord: 'Gaz' },
    { category: 'Elementler ve Kimya', citizenWord: 'Molekül', imposterWord: 'Atom' },
    { category: 'Matematik ve Geometri', citizenWord: 'Kare', imposterWord: 'Dikdörtgen' },
    { category: 'Matematik ve Geometri', citizenWord: 'Üçgen', imposterWord: 'Piramit' },
    { category: 'Matematik ve Geometri', citizenWord: 'Çember', imposterWord: 'Elips' },
    { category: 'Matematik ve Geometri', citizenWord: 'Küp', imposterWord: 'Küre' },
    { category: 'Matematik ve Geometri', citizenWord: 'Toplama', imposterWord: 'Çıkarma' },
    { category: 'Matematik ve Geometri', citizenWord: 'Çarpma', imposterWord: 'Bölme' },
    { category: 'Matematik ve Geometri', citizenWord: 'Denklem', imposterWord: 'Formül' },
    { category: 'Matematik ve Geometri', citizenWord: 'Alan', imposterWord: 'Çevre' },
    { category: 'Matematik ve Geometri', citizenWord: 'Yarıçap', imposterWord: 'Çap' },
    { category: 'Matematik ve Geometri', citizenWord: 'Sinüs', imposterWord: 'Kosinüs' },
    { category: 'Matematik ve Geometri', citizenWord: 'Logaritma', imposterWord: 'İntegral' },
    { category: 'Matematik ve Geometri', citizenWord: 'Türev', imposterWord: 'Limit' },
    { category: 'Matematik ve Geometri', citizenWord: 'Tek Sayı', imposterWord: 'Çift Sayı' },
    { category: 'Matematik ve Geometri', citizenWord: 'Asal Sayı', imposterWord: 'Doğal Sayı' },
    { category: 'Matematik ve Geometri', citizenWord: 'Prizma', imposterWord: 'Silindir' },
    { category: 'Matematik ve Geometri', citizenWord: 'Kök', imposterWord: 'Kuvvet' },
    { category: 'Matematik ve Geometri', citizenWord: 'Küme', imposterWord: 'Grup' },
    { category: 'Matematik ve Geometri', citizenWord: 'Matris', imposterWord: 'Vektör' },
    { category: 'Mobilya', citizenWord: 'Masa', imposterWord: 'Sehpa' },
    { category: 'Mobilya', citizenWord: 'Sandalye', imposterWord: 'Tabure' },
    { category: 'Mobilya', citizenWord: 'Yatak', imposterWord: 'Baza' },
    { category: 'Mobilya', citizenWord: 'Gardırop', imposterWord: 'Şifonyer' },
    { category: 'Mobilya', citizenWord: 'Kitaplık', imposterWord: 'Raf' },
    { category: 'Mobilya', citizenWord: 'Halı', imposterWord: 'Kilim' },
    { category: 'Mobilya', citizenWord: 'Perde', imposterWord: 'Tül' },
    { category: 'Mobilya', citizenWord: 'Ayna', imposterWord: 'Boy Aynası' },
    { category: 'Mobilya', citizenWord: 'Kırlent', imposterWord: 'Yastık' },
    { category: 'Mobilya', citizenWord: 'Vestiyer', imposterWord: 'Askılık' },
    { category: 'Mobilya', citizenWord: 'Komodin', imposterWord: 'Şifonyer' },
    { category: 'Mobilya', citizenWord: 'Puf', imposterWord: 'Minder' },
    { category: 'Mobilya', citizenWord: 'Avize', imposterWord: 'Lamba' },
    { category: 'Mobilya', citizenWord: 'Abajur', imposterWord: 'Lambader' },
    { category: 'Mobilya', citizenWord: 'Vitrin', imposterWord: 'Gümüşlük' },
    { category: 'Mobilya', citizenWord: 'Portmanto', imposterWord: 'Ayakkabılık' },
    { category: 'Mobilya', citizenWord: 'Beşik', imposterWord: 'Puset' },
    { category: 'Kırtasiye', citizenWord: 'Defter', imposterWord: 'Ajanda' },
    { category: 'Kırtasiye', citizenWord: 'Silgi', imposterWord: 'Daksil' },
    { category: 'Kırtasiye', citizenWord: 'Dosya', imposterWord: 'Klasör' },
    { category: 'Kırtasiye', citizenWord: 'Kitap', imposterWord: 'Dergi' },
    { category: 'Kırtasiye', citizenWord: 'Makas', imposterWord: 'Maket Bıçağı' },
    { category: 'Kırtasiye', citizenWord: 'Zımba', imposterWord: 'Delgeç' },
    { category: 'Kırtasiye', citizenWord: 'Boya Kalemi', imposterWord: 'Pastel Boya' },
    { category: 'Kırtasiye', citizenWord: 'Yapıştırıcı', imposterWord: 'Bant' },
    { category: 'Kırtasiye', citizenWord: 'Cetvel', imposterWord: 'Gönye' },
    { category: 'Kırtasiye', citizenWord: 'Ataş', imposterWord: 'Raptiye' },
    { category: 'Kırtasiye', citizenWord: 'Etiket', imposterWord: 'Post-it' },
    { category: 'Kırtasiye', citizenWord: 'Hesap Makinesi', imposterWord: 'Abaküs' },
    { category: 'Kırtasiye', citizenWord: 'Tuval', imposterWord: 'Şövale' },
    { category: 'Kırtasiye', citizenWord: 'Dosya Kağıdı', imposterWord: 'Saman Kağıdı' },
    { category: 'Kırtasiye', citizenWord: 'Mürekkep', imposterWord: 'Kartuş' },
    { category: 'Kırtasiye', citizenWord: 'Fırça', imposterWord: 'Sulu Boya' },
    { category: 'Kırtasiye', citizenWord: 'Harita', imposterWord: 'Küre' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Sabun', imposterWord: 'Deterjan' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Süpürge', imposterWord: 'Vileda' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Çamaşır Suyu', imposterWord: 'Yumuşatıcı' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Sünger', imposterWord: 'Tel' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Bez', imposterWord: 'Mop' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Şampuan', imposterWord: 'Duş Jeli' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Diş Macunu', imposterWord: 'Ağız Çalkalama Suyu' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Faraş', imposterWord: 'Fırça' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Kova', imposterWord: 'Leğen' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Yüzey Temizleyici', imposterWord: 'Camsil' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Eldiven', imposterWord: 'Maske' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Kireç Çözücü', imposterWord: 'Yağ Çözücü' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Parfüm', imposterWord: 'Oda Kokusu' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Kağıt Havlu', imposterWord: 'Peçete' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Islak Mendil', imposterWord: 'Kolonya' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Toz Bezi', imposterWord: 'Mikrofiber Bez' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Ütü', imposterWord: 'Buhar Makinesi' },
    { category: 'Temizlik Malzemeleri', citizenWord: 'Elektrikli Süpürge', imposterWord: 'Robot Süpürge' },
    { category: 'Banyo Eşyaları', citizenWord: 'Havlu', imposterWord: 'Bornoz' },
    { category: 'Banyo Eşyaları', citizenWord: 'Küvet', imposterWord: 'Duşakabin' },
    { category: 'Banyo Eşyaları', citizenWord: 'Klozet', imposterWord: 'Pisuvar' },
    { category: 'Banyo Eşyaları', citizenWord: 'Diş Fırçası', imposterWord: 'Elektrikli Diş Fırçası' },
    { category: 'Banyo Eşyaları', citizenWord: 'Lif', imposterWord: 'Kese' },
    { category: 'Banyo Eşyaları', citizenWord: 'Tarak', imposterWord: 'Fırça' },
    { category: 'Banyo Eşyaları', citizenWord: 'Ayna', imposterWord: 'Dolap' },
    { category: 'Banyo Eşyaları', citizenWord: 'Paspas', imposterWord: 'Halı' },
    { category: 'Banyo Eşyaları', citizenWord: 'Sıvı Sabun', imposterWord: 'Kalıp Sabun' },
    { category: 'Banyo Eşyaları', citizenWord: 'Şofben', imposterWord: 'Kombi' },
    { category: 'Banyo Eşyaları', citizenWord: 'Çamaşır Makinesi', imposterWord: 'Kurutma Makinesi' },
    { category: 'Banyo Eşyaları', citizenWord: 'Ayak Havlusu', imposterWord: 'Paspas' },
    { category: 'Banyo Eşyaları', citizenWord: 'Sabunluk', imposterWord: 'Diş Fırçalık' },
    { category: 'Banyo Eşyaları', citizenWord: 'Banyo Perdesi', imposterWord: 'Cam Bölme' },
    { category: 'Banyo Eşyaları', citizenWord: 'Cımbız', imposterWord: 'Tırnak Makası' },
    { category: 'Banyo Eşyaları', citizenWord: 'Vücut Losyonu', imposterWord: 'Nemlendirici' },
    { category: 'Banyo Eşyaları', citizenWord: 'Pamuk', imposterWord: 'Kulak Çubuğu' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Ketıl', imposterWord: 'Çaycı' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Tost Makinesi', imposterWord: 'Waffle Makinesi' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Blender', imposterWord: 'Mikser' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Fritöz', imposterWord: 'Airfryer' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Kahve Makinesi', imposterWord: 'Espresso Makinesi' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Rende', imposterWord: 'Doğrayıcı' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Süzgeç', imposterWord: 'Elek' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Kepçe', imposterWord: 'Kevgir' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Çırpıcı', imposterWord: 'Spatula' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Tuzluk', imposterWord: 'Biberlik' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Ekmek Kızartma Makinesi', imposterWord: 'Fırın' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Termos', imposterWord: 'Matara' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Cezve', imposterWord: 'Demlik' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Tepsi', imposterWord: 'Tabak' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Mutfak Tartısı', imposterWord: 'Ölçü Kabı' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Düdüklü Tencere', imposterWord: 'Güveç' },
    { category: 'Mutfak ve Aletler', citizenWord: 'Çöp Öğütücü', imposterWord: 'Bulaşık Makinesi' },
    { category: 'Masa Oyunları', citizenWord: 'Satranç', imposterWord: 'Dama' },
    { category: 'Masa Oyunları', citizenWord: 'Tavla', imposterWord: 'Okey' },
    { category: 'Masa Oyunları', citizenWord: 'Tabu', imposterWord: 'Anlat Bakalım' },
    { category: 'Masa Oyunları', citizenWord: 'Jenga', imposterWord: 'Mikado' },
    { category: 'Masa Oyunları', citizenWord: 'Scrabble', imposterWord: 'Kelime Oyunu' },
    { category: 'Masa Oyunları', citizenWord: 'Kızma Birader', imposterWord: 'Ludo' },
    { category: 'Masa Oyunları', citizenWord: 'Domino', imposterWord: 'Mahjong' },
    { category: 'Masa Oyunları', citizenWord: 'Milyarder', imposterWord: 'Metropol' },
    { category: 'Masa Oyunları', citizenWord: 'XOX', imposterWord: 'Üç Taş' },
    { category: 'Masa Oyunları', citizenWord: 'Trivial Pursuit', imposterWord: 'Bilgi Yarışması' },
    { category: 'Masa Oyunları', citizenWord: 'Catan', imposterWord: 'Carcassonne' },
    { category: 'Masa Oyunları', citizenWord: 'Puzzle', imposterWord: 'Lego' },
    { category: 'Masa Oyunları', citizenWord: 'Maket', imposterWord: 'Model' },
    { category: 'Masa Oyunları', citizenWord: 'Langırt', imposterWord: 'Hava Hokeyi' },
    { category: 'Masa Oyunları', citizenWord: 'Bilardo', imposterWord: 'Snooker' },
    { category: 'Masa Oyunları', citizenWord: 'Dart', imposterWord: 'Okçuluk' },
    { category: 'Masa Oyunları', citizenWord: 'Bowling', imposterWord: 'Lobut' },
    { category: 'Dijital Oyunlar', citizenWord: 'Minecraft', imposterWord: 'Roblox' },
    { category: 'Dijital Oyunlar', citizenWord: 'PUBG', imposterWord: 'Fortnite' },
    { category: 'Dijital Oyunlar', citizenWord: 'FIFA', imposterWord: 'PES' },
    { category: 'Dijital Oyunlar', citizenWord: 'League of Legends', imposterWord: 'Dota 2' },
    { category: 'Dijital Oyunlar', citizenWord: 'GTA', imposterWord: 'Red Dead Redemption' },
    { category: 'Dijital Oyunlar', citizenWord: 'Counter-Strike', imposterWord: 'Valorant' },
    { category: 'Dijital Oyunlar', citizenWord: 'Among Us', imposterWord: 'Vampir Köylü' },
    { category: 'Dijital Oyunlar', citizenWord: 'The Sims', imposterWord: 'Second Life' },
    { category: 'Dijital Oyunlar', citizenWord: 'Candy Crush', imposterWord: 'Tetris' },
    { category: 'Dijital Oyunlar', citizenWord: 'Call of Duty', imposterWord: 'Battlefield' },
    { category: 'Dijital Oyunlar', citizenWord: 'World of Warcraft', imposterWord: 'Knight Online' },
    { category: 'Dijital Oyunlar', citizenWord: 'Clash of Clans', imposterWord: 'Clash Royale' },
    { category: 'Dijital Oyunlar', citizenWord: 'Brawl Stars', imposterWord: 'Stumble Guys' },
    { category: 'Dijital Oyunlar', citizenWord: 'Need for Speed', imposterWord: 'Forza Horizon' },
    { category: 'Dijital Oyunlar', citizenWord: 'God of War', imposterWord: 'Elden Ring' },
    { category: 'Dijital Oyunlar', citizenWord: 'Super Mario', imposterWord: 'Sonic' },
    { category: 'Dijital Oyunlar', citizenWord: 'Pac-Man', imposterWord: 'Snake' },
    { category: 'Dijital Oyunlar', citizenWord: 'Angry Birds', imposterWord: 'Fruit Ninja' },
    { category: 'Dijital Oyunlar', citizenWord: 'Subway Surfers', imposterWord: 'Temple Run' },
    { category: 'Dijital Oyunlar', citizenWord: 'Pokémon', imposterWord: 'Digimon' },
    { category: 'Açık Hava', citizenWord: 'Kamp', imposterWord: 'Piknik' },
    { category: 'Açık Hava', citizenWord: 'Yürüyüş', imposterWord: 'Koşu' },
    { category: 'Açık Hava', citizenWord: 'Balık Tutma', imposterWord: 'Avcılık' },
    { category: 'Açık Hava', citizenWord: 'Kaykay', imposterWord: 'Paten' },
    { category: 'Açık Hava', citizenWord: 'Uçurtma', imposterWord: 'Model Uçak' },
    { category: 'Açık Hava', citizenWord: 'Dağcılık', imposterWord: 'Kaya Tırmanışı' },
    { category: 'Açık Hava', citizenWord: 'Bisiklet', imposterWord: 'Scooter' },
    { category: 'Açık Hava', citizenWord: 'Yüzme', imposterWord: 'Dalış' },
    { category: 'Açık Hava', citizenWord: 'Sörf', imposterWord: 'Yelken' },
    { category: 'Açık Hava', citizenWord: 'Kano', imposterWord: 'Rafting' },
    { category: 'Açık Hava', citizenWord: 'Bahçecilik', imposterWord: 'Çiftçilik' },
    { category: 'Açık Hava', citizenWord: 'Yoga', imposterWord: 'Pilates' },
    { category: 'Açık Hava', citizenWord: 'Meditasyon', imposterWord: 'Nefes Egzersizi' },
    { category: 'Açık Hava', citizenWord: 'Paintball', imposterWord: 'Lazer Tag' },
    { category: 'Açık Hava', citizenWord: 'Bungee Jumping', imposterWord: 'Paraşüt' },
    { category: 'Açık Hava', citizenWord: 'Safari', imposterWord: 'Doğa Gezisi' },
    { category: 'Açık Hava', citizenWord: 'Kayak', imposterWord: 'Snowboard' },
    { category: 'Açık Hava', citizenWord: 'Kızak', imposterWord: 'Buz Pateni' },
    { category: 'Açık Hava', citizenWord: 'At Binme', imposterWord: 'Fayton Turu' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Pul', imposterWord: 'Para' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Antika', imposterWord: 'Eski Eşya' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Örgü', imposterWord: 'Dantel' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Dikiş', imposterWord: 'Nakış' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Resim', imposterWord: 'Boyama' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Seramik', imposterWord: 'Heykel' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Fotoğrafçılık', imposterWord: 'Videografi' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Ebru', imposterWord: 'Sulu Boya' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Lego', imposterWord: 'Yapboz' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Takı Tasarımı', imposterWord: 'Boncuk İşleme' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Ahşap Boyama', imposterWord: 'Dekupaj' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Koleksiyon', imposterWord: 'Arşiv' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Plak', imposterWord: 'Kaset' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Kar Küresi', imposterWord: 'Biblo' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Magnet', imposterWord: 'Anahtarlık' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Çizgi Roman', imposterWord: 'Manga' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Günlük Tutma', imposterWord: 'Blog Yazma' },
    { category: 'Koleksiyon ve Sanat', citizenWord: 'Podcast', imposterWord: 'Radyo' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Pişti', imposterWord: 'Batak' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Poker', imposterWord: 'Blackjack' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Briç', imposterWord: 'Konken' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Sudoku', imposterWord: 'Kakuro' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Bulmaca', imposterWord: 'Kare Bulmaca' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Çengel Bulmaca', imposterWord: 'Kelime Avı' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Bilmece', imposterWord: 'Tekerleme' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Tangram', imposterWord: 'Pentomino' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Satranç Problemi', imposterWord: 'Mat' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Sayısal Loto', imposterWord: 'Piyango' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Uno', imposterWord: 'Solo Test' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Sihirbazlık', imposterWord: 'İllüzyon' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Zar Atma', imposterWord: 'Yazı Tura' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Sessiz Sinema', imposterWord: 'Kulaktan Kulağa' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'İsim Şehir', imposterWord: 'Kim Kiminle' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Doğruluk mu Cesaret mi', imposterWord: 'Şişe Çevirme' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Kelime Zinciri', imposterWord: 'Adam Asmaca' },
    { category: 'Zeka ve Kart Oyunları', citizenWord: 'Labirent', imposterWord: 'Kaçış Oyunu' },
    { category: 'Duygular', citizenWord: 'Korku', imposterWord: 'Endişe' },
    { category: 'Duygular', citizenWord: 'Gurur', imposterWord: 'Kibir' },
    { category: 'Duygular', citizenWord: 'Yalnızlık', imposterWord: 'Issızlık' },
    { category: 'Duygular', citizenWord: 'Güven', imposterWord: 'Sadakat' },
    { category: 'Duygular', citizenWord: 'Nefret', imposterWord: 'Kin' },
    { category: 'Duygular', citizenWord: 'Umut', imposterWord: 'Beklenti' },
    { category: 'Duygular', citizenWord: 'Pişmanlık', imposterWord: 'Vicdan Azabı' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Sabah', imposterWord: 'Şafak' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Akşam', imposterWord: 'Gece' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Dakika', imposterWord: 'Saniye' },
    { category: 'Zaman ve Dönemler', citizenWord: 'An', imposterWord: 'Saniyelik' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Dün', imposterWord: 'Geçen Gün' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Yarın', imposterWord: 'Gelecek Gün' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Mevsim', imposterWord: 'Ay' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Gündüz', imposterWord: 'Aydınlık' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Alacakaranlık', imposterWord: 'Gün Batımı' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Çocukluk', imposterWord: 'Gençlik' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Yaşlılık', imposterWord: 'Emeklilik' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Yılbaşı', imposterWord: 'Bayram' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Tatil', imposterWord: 'Mola' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Hafta içi', imposterWord: 'Hafta sonu' },
    { category: 'Zaman ve Dönemler', citizenWord: 'Öğle', imposterWord: 'İkindi' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Sarı', imposterWord: 'Turuncu' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Mavi', imposterWord: 'Lacivert' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Kırmızı', imposterWord: 'Bordo' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Pembe', imposterWord: 'Fuşya' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Yeşil', imposterWord: 'Turkuaz' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Gri', imposterWord: 'Füme' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Beyaz', imposterWord: 'Krem' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Siyah', imposterWord: 'Kömür Rengi' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Sert', imposterWord: 'Katı' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Yumuşak', imposterWord: 'Esnek' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Yavaş', imposterWord: 'Ağır' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Sıcak', imposterWord: 'Ilık' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Soğuk', imposterWord: 'Serin' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Güzel', imposterWord: 'Çekici' },
    { category: 'Nitelikler ve Renkler', citizenWord: 'Zayıf', imposterWord: 'İnce' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Hayal', imposterWord: 'Rüya' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Yalan', imposterWord: 'İftira' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Zeka', imposterWord: 'Akıl' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Mantık', imposterWord: 'Sağduyu' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Bilgi', imposterWord: 'Veri' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'İnanç', imposterWord: 'İtimat' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Adalet', imposterWord: 'Eşitlik' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Vicdan', imposterWord: 'Ahlak' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Başarı', imposterWord: 'Zafer' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Hata', imposterWord: 'Kusur' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Teori', imposterWord: 'Varsayım' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Kader', imposterWord: 'Kısmet' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Şans', imposterWord: 'Talih' },
    { category: 'Düşünce ve Felsefe', citizenWord: 'Sır', imposterWord: 'Gizem' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Düşman', imposterWord: 'Rakip' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Aile', imposterWord: 'Akraba' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Komşu', imposterWord: 'Tanıdık' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Kültür', imposterWord: 'Gelenek' },
    { category: 'Sosyal Kavramlar', citizenWord: 'İş', imposterWord: 'Meslek' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Savaş', imposterWord: 'Çatışma' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Barış', imposterWord: 'Uzlaşma' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Yardım', imposterWord: 'Destek' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Borç', imposterWord: 'Alacak' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Ceza', imposterWord: 'Ödül' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Kavga', imposterWord: 'Tartışma' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Düğün', imposterWord: 'Nişan' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Cenaze', imposterWord: 'Yas' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Şöhret', imposterWord: 'İtibar' },
    { category: 'Sosyal Kavramlar', citizenWord: 'Gurbet', imposterWord: 'Sıla' },
    { category: 'Süper Kahramanlar', citizenWord: 'Superman', imposterWord: 'Batman' },
    { category: 'Süper Kahramanlar', citizenWord: 'Spider-Man', imposterWord: 'Iron Man' },
    { category: 'Süper Kahramanlar', citizenWord: 'Hulk', imposterWord: 'Thor' },
    { category: 'Süper Kahramanlar', citizenWord: 'Wonder Woman', imposterWord: 'Captain Marvel' },
    { category: 'Süper Kahramanlar', citizenWord: 'Flash', imposterWord: 'Quicksilver' },
    { category: 'Süper Kahramanlar', citizenWord: 'Joker', imposterWord: 'Thanos' },
    { category: 'Süper Kahramanlar', citizenWord: 'Avengers', imposterWord: 'Justice League' },
    { category: 'Süper Kahramanlar', citizenWord: 'Marvel', imposterWord: 'DC' },
    { category: 'Süper Kahramanlar', citizenWord: 'Aquaman', imposterWord: 'Namor' },
    { category: 'Süper Kahramanlar', citizenWord: 'Black Widow', imposterWord: 'Catwoman' },
    { category: 'Süper Kahramanlar', citizenWord: 'Wolverine', imposterWord: 'Deadpool' },
    { category: 'Süper Kahramanlar', citizenWord: 'Robin', imposterWord: 'Nightwing' },
    { category: 'Süper Kahramanlar', citizenWord: 'X-Men', imposterWord: 'Fantastic Four' },
    { category: 'Süper Kahramanlar', citizenWord: 'Ant-Man', imposterWord: 'Wasp' },
    { category: 'Süper Kahramanlar', citizenWord: 'Black Panther', imposterWord: 'Black Adam' },
    { category: 'Süper Kahramanlar', citizenWord: 'Doctor Strange', imposterWord: 'Scarlet Witch' },
    { category: 'Süper Kahramanlar', citizenWord: 'Green Lantern', imposterWord: 'Silver Surfer' },
    { category: 'Süper Kahramanlar', citizenWord: 'Venom', imposterWord: 'Carnage' },
    { category: 'Süper Kahramanlar', citizenWord: 'Batmobile', imposterWord: 'Quinjet' },
    { category: 'Süper Kahramanlar', citizenWord: 'Gotham', imposterWord: 'Metropolis' },
    { category: 'Sosyal Medya', citizenWord: 'Instagram', imposterWord: 'TikTok' },
    { category: 'Sosyal Medya', citizenWord: 'Twitter (X)', imposterWord: 'Threads' },
    { category: 'Sosyal Medya', citizenWord: 'Facebook', imposterWord: 'LinkedIn' },
    { category: 'Sosyal Medya', citizenWord: 'Snapchat', imposterWord: 'Instagram' },
    { category: 'Sosyal Medya', citizenWord: 'YouTube', imposterWord: 'Vimeo' },
    { category: 'Sosyal Medya', citizenWord: 'WhatsApp', imposterWord: 'Telegram' },
    { category: 'Sosyal Medya', citizenWord: 'Pinterest', imposterWord: 'Tumblr' },
    { category: 'Sosyal Medya', citizenWord: 'Reddit', imposterWord: 'Discord' },
    { category: 'Sosyal Medya', citizenWord: 'Spotify', imposterWord: 'Apple Music' },
    { category: 'Sosyal Medya', citizenWord: 'Twitch', imposterWord: 'Kick' },
    { category: 'Sosyal Medya', citizenWord: 'Zoom', imposterWord: 'Skype' },
    { category: 'Sosyal Medya', citizenWord: 'Tinder', imposterWord: 'Bumble' },
    { category: 'Sosyal Medya', citizenWord: 'BeReal', imposterWord: 'Snapchat' },
    { category: 'Sosyal Medya', citizenWord: 'Messenger', imposterWord: 'Signal' },
    { category: 'Sosyal Medya', citizenWord: 'Medium', imposterWord: 'Substack' },
    { category: 'Sosyal Medya', citizenWord: 'OnlyFans', imposterWord: 'Patreon' },
    { category: 'Sosyal Medya', citizenWord: 'Clubhouse', imposterWord: 'Twitter Spaces' },
    { category: 'Sosyal Medya', citizenWord: 'Yelp', imposterWord: 'Tripadvisor' },
    { category: 'Sosyal Medya', citizenWord: 'Tiktok', imposterWord: 'Reels' },
    { category: 'Fast Food', citizenWord: 'Burger King', imposterWord: 'McDonalds' },
    { category: 'Fast Food', citizenWord: 'KFC', imposterWord: 'Popeyes' },
    { category: 'Fast Food', citizenWord: 'Dominos', imposterWord: 'Pizza Hut' },
    { category: 'Fast Food', citizenWord: 'Starbucks', imposterWord: 'Costa Coffee' },
    { category: 'Fast Food', citizenWord: 'Subway', imposterWord: 'Arbys' },
    { category: 'Fast Food', citizenWord: 'Simit Sarayı', imposterWord: 'Kahve Dünyası' },
    { category: 'Fast Food', citizenWord: 'Popeyes', imposterWord: 'Texas Chicken' },
    { category: 'Fast Food', citizenWord: 'Baydöner', imposterWord: 'HD İskender' },
    { category: 'Fast Food', citizenWord: 'Tavuk Dünyası', imposterWord: 'Köfteci Yusuf' },
    { category: 'Fast Food', citizenWord: 'Little Caesars', imposterWord: 'Papa Johns' },
    { category: 'Fast Food', citizenWord: 'Pizza Pizza', imposterWord: 'Sbarro' },
    { category: 'Fast Food', citizenWord: 'Krispy Kreme', imposterWord: 'Dunkin Donuts' },
    { category: 'Fast Food', citizenWord: 'Shake Shack', imposterWord: 'Five Guys' },
    { category: 'Fast Food', citizenWord: 'PizzaLazza', imposterWord: 'Pasaport Pizza' },
    { category: 'Fast Food', citizenWord: 'Gloria Jeans', imposterWord: 'Tchibo' },
    { category: 'Fast Food', citizenWord: 'EspressoLab', imposterWord: 'Brew Coffeeworks' },
    { category: 'Fast Food', citizenWord: 'Waffle Stop', imposterWord: 'Abbas Waffle' },
    { category: 'Fast Food', citizenWord: 'Komagene', imposterWord: 'Oses' },
    { category: 'Fast Food', citizenWord: 'Mado', imposterWord: 'Özsüt' },
    { category: 'Araba Markaları', citizenWord: 'BMW', imposterWord: 'Mercedes' },
    { category: 'Araba Markaları', citizenWord: 'Ferrari', imposterWord: 'Lamborghini' },
    { category: 'Araba Markaları', citizenWord: 'Tesla', imposterWord: 'Togg' },
    { category: 'Araba Markaları', citizenWord: 'Toyota', imposterWord: 'Honda' },
    { category: 'Araba Markaları', citizenWord: 'Audi', imposterWord: 'Volkswagen' },
    { category: 'Araba Markaları', citizenWord: 'Porsche', imposterWord: 'Maserati' },
    { category: 'Araba Markaları', citizenWord: 'Ford', imposterWord: 'Fiat' },
    { category: 'Araba Markaları', citizenWord: 'Volvo', imposterWord: 'Saab' },
    { category: 'Araba Markaları', citizenWord: 'Jeep', imposterWord: 'Land Rover' },
    { category: 'Araba Markaları', citizenWord: 'Bugatti', imposterWord: 'Pagani' },
    { category: 'Araba Markaları', citizenWord: 'Hyundai', imposterWord: 'Kia' },
    { category: 'Araba Markaları', citizenWord: 'Renault', imposterWord: 'Dacia' },
    { category: 'Araba Markaları', citizenWord: 'Peugeot', imposterWord: 'Citroen' },
    { category: 'Araba Markaları', citizenWord: 'Nissan', imposterWord: 'Mazda' },
    { category: 'Araba Markaları', citizenWord: 'Chevrolet', imposterWord: 'Dodge' },
    { category: 'Araba Markaları', citizenWord: 'Bentley', imposterWord: 'Rolls-Royce' },
    { category: 'Araba Markaları', citizenWord: 'Alfa Romeo', imposterWord: 'Lancia' },
    { category: 'Araba Markaları', citizenWord: 'Skoda', imposterWord: 'Seat' },
    { category: 'Araba Markaları', citizenWord: 'Mini Cooper', imposterWord: 'Fiat 500' },
    { category: 'Araba Markaları', citizenWord: 'Aston Martin', imposterWord: 'Jaguar' },
    { category: 'Teknoloji & Dijital', citizenWord: 'iPhone', imposterWord: 'Samsung Galaxy' },
    { category: 'Teknoloji & Dijital', citizenWord: 'PlayStation', imposterWord: 'Xbox' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Nintendo Switch', imposterWord: 'Steam Deck' },
    { category: 'Teknoloji & Dijital', citizenWord: 'MacBook', imposterWord: 'iPad' },
    { category: 'Teknoloji & Dijital', citizenWord: 'AirPods', imposterWord: 'Galaxy Buds' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Dyson', imposterWord: 'Xiaomi Süpürge' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Amazon', imposterWord: 'Trendyol' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Google', imposterWord: 'Bing' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Windows', imposterWord: 'macOS' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Netflix', imposterWord: 'Disney+' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Amazon Prime', imposterWord: 'BluTV' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Hepsiburada', imposterWord: 'Getir' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Uber', imposterWord: 'Martı' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Zoom', imposterWord: 'Microsoft Teams' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Photoshop', imposterWord: 'Canva' },
    { category: 'Teknoloji & Dijital', citizenWord: 'ChatGPT', imposterWord: 'Gemini' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Intel', imposterWord: 'AMD' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Nvidia', imposterWord: 'Radeon' },
    { category: 'Teknoloji & Dijital', citizenWord: 'Sony', imposterWord: 'Panasonic' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Zeus', imposterWord: 'Odin' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Poseidon', imposterWord: 'Hades' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Herkül', imposterWord: 'Aşil' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Athena', imposterWord: 'Artemis' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Afrodit', imposterWord: 'Hera' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Anubis', imposterWord: 'Osiris' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Thor', imposterWord: 'Loki' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Medusa', imposterWord: 'Deniz Kızı' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Pegasus', imposterWord: 'Ejderha' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Truva Atı', imposterWord: 'Sfenks' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Olympos Dağı', imposterWord: 'Asgard' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Şahmeran', imposterWord: 'Medusa' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Hızır', imposterWord: 'Dede Korkut' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Prometheus', imposterWord: 'Pandora' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Minotor', imposterWord: 'Siren' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Sfenks', imposterWord: 'Piramit' },
    { category: 'Mitolojik Karakterler', citizenWord: 'Ragnarok', imposterWord: 'Kıyamet' },
    { category: 'Tarihi Dönemler', citizenWord: 'Orta Çağ', imposterWord: 'Yeni Çağ' },
    { category: 'Tarihi Dönemler', citizenWord: 'Taş Devri', imposterWord: 'Maden Devri' },
    { category: 'Tarihi Dönemler', citizenWord: 'Rönesans', imposterWord: 'Reform' },
    { category: 'Tarihi Dönemler', citizenWord: 'Sanayi Devrimi', imposterWord: 'Fransız İhtilali' },
    { category: 'Tarihi Dönemler', citizenWord: 'Kurtuluş Savaşı', imposterWord: 'Çanakkale Savaşı' },
    { category: 'Tarihi Dönemler', citizenWord: 'Lale Devri', imposterWord: 'Tanzimat Dönemi' },
    { category: 'Tarihi Dönemler', citizenWord: 'Buzul Çağı', imposterWord: 'İlk Çağ' },
    { category: 'Tarihi Dönemler', citizenWord: 'Cilalı Taş Devri', imposterWord: 'Yontma Taş Devri' },
    { category: 'Tarihi Dönemler', citizenWord: 'Fetret Devri', imposterWord: 'Duraklama Dönemi' },
    { category: 'Tarihi Dönemler', citizenWord: 'Soğuk Savaş', imposterWord: 'Vietnam Savaşı' },
    { category: 'Tarihi Dönemler', citizenWord: '1. Dünya Savaşı', imposterWord: '2. Dünya Savaşı' },
    { category: 'Tarihi Dönemler', citizenWord: 'Büyük Buhran', imposterWord: 'Enflasyon' },
    { category: 'Tarihi Dönemler', citizenWord: 'Meşrutiyet', imposterWord: 'Cumhuriyet' },
    { category: 'Tarihi Dönemler', citizenWord: 'Antik Çağ', imposterWord: 'Helenistik Dönem' },
    { category: 'Tarihi Dönemler', citizenWord: 'Demir Çağı', imposterWord: 'Tunç Çağı' },
    { category: 'Tarihi Dönemler', citizenWord: 'Padişahlık', imposterWord: 'Krallık' },
    { category: 'Tarihi Dönemler', citizenWord: 'Aydınlanma Çağı', imposterWord: 'Bilim Devrimi' },
    { category: 'Tarihi Dönemler', citizenWord: 'Osmanlı İmparatorluğu', imposterWord: 'Bizans İmparatorluğu' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Kılıç', imposterWord: 'Kalkan' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Top', imposterWord: 'Tüfek' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Mızrak', imposterWord: 'Gürz' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Yeniçeri', imposterWord: 'Şövalye' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Samuray', imposterWord: 'Ninja' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Tank', imposterWord: 'Zırhlı Araç' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Gemi', imposterWord: 'Denizaltı' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Uçak', imposterWord: 'Helikopter' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Tabanca', imposterWord: 'Tüfek' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Mancınık', imposterWord: 'Koçbaşı' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Zırh', imposterWord: 'Kalkan' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Barut', imposterWord: 'Dinamit' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Süvari', imposterWord: 'Piyade' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Okçu', imposterWord: 'Nişancı' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Hançer', imposterWord: 'Bıçak' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Miğfer', imposterWord: 'Kask' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Kale', imposterWord: 'Sur' },
    { category: 'Savaş Aletleri & Birimler', citizenWord: 'Siper', imposterWord: 'Hendek' },
    { category: 'Tarihi Kişiler', citizenWord: 'Atatürk', imposterWord: 'İsmet İnönü' },
    { category: 'Tarihi Kişiler', citizenWord: 'Fatih Sultan Mehmet', imposterWord: 'Yavuz Sultan Selim' },
    { category: 'Tarihi Kişiler', citizenWord: 'Kanuni Sultan Süleyman', imposterWord: 'IV. Murat' },
    { category: 'Tarihi Kişiler', citizenWord: 'Napolyon', imposterWord: 'Sezar' },
    { category: 'Tarihi Kişiler', citizenWord: 'Cengiz Han', imposterWord: 'Attila' },
    { category: 'Tarihi Kişiler', citizenWord: 'Mimar Sinan', imposterWord: 'Leonardo da Vinci' },
    { category: 'Tarihi Kişiler', citizenWord: 'Einstein', imposterWord: 'Newton' },
    { category: 'Tarihi Kişiler', citizenWord: 'Mevlana', imposterWord: 'Yunus Emre' },
    { category: 'Tarihi Kişiler', citizenWord: 'Hazerfen Ahmed Çelebi', imposterWord: 'Evliya Çelebi' },
    { category: 'Tarihi Kişiler', citizenWord: 'İbn-i Sina', imposterWord: 'Farabi' },
    { category: 'Tarihi Kişiler', citizenWord: 'Osman Bey', imposterWord: 'Ertuğrul Gazi' },
    { category: 'Tarihi Kişiler', citizenWord: 'Kleopatra', imposterWord: 'Nefertiti' },
    { category: 'Tarihi Kişiler', citizenWord: 'Kristof Kolomb', imposterWord: 'Vasco da Gama' },
    { category: 'Tarihi Kişiler', citizenWord: 'Alexander Graham Bell', imposterWord: 'Thomas Edison' },
    { category: 'Tarihi Kişiler', citizenWord: 'Marco Polo', imposterWord: 'Macellan' },
    { category: 'Tarihi Kişiler', citizenWord: 'Sultan Alparslan', imposterWord: 'Melikşah' },
    { category: 'Tarihi Kişiler', citizenWord: 'Hannibal', imposterWord: 'Spartaküs' },
    { category: 'Tarihi Kişiler', citizenWord: 'Viktor Hugo', imposterWord: 'Shakespeare' },
    { category: 'Tarihi Kişiler', citizenWord: 'Mete Han', imposterWord: 'Bilge Kağan' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Roma', imposterWord: 'Bizans' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Mısır', imposterWord: 'Mezopotamya' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Aztekler', imposterWord: 'Mayalar' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Hititler', imposterWord: 'Urartular' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Sümerler', imposterWord: 'Babiller' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Truva', imposterWord: 'Sparta' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Piramitler', imposterWord: 'Tapınaklar' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Kolezyum', imposterWord: 'Ayasofya' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Çin Seddi', imposterWord: 'Tac Mahal' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Efes', imposterWord: 'Bergama' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Anıtkabir', imposterWord: 'TBMM' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Topkapı Sarayı', imposterWord: 'Dolmabahçe Sarayı' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Kudüs', imposterWord: 'Mekke' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Atina', imposterWord: 'Roma' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'İpek Yolu', imposterWord: 'Baharat Yolu' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'İnka Medeniyeti', imposterWord: 'Maya Medeniyeti' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Vikingler', imposterWord: 'Moğollar' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Kütüphane', imposterWord: 'Müze' },
    { category: 'Medeniyetler & Mekanlar', citizenWord: 'Köy', imposterWord: 'Oba' }
];
